services:
  mongodb:
    image: mongo:latest
    container_name: smartcampus_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: smartcampus_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mongo_data: